services:
  mnemosyne:
    image: postgres:16
    environment:
      POSTGRES_USER: mnemosyne
      POSTGRES_PASSWORD: S@MPL_P4SSW0RD
      POSTGRES_DB: mnemosyne
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
